name: PR Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Labels Based on Conventional Commits
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();

            if (title.startsWith('feat')) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['feature'], // Label for features
              });
            } else if (title.startsWith('fix')) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['fix', 'bug'], // Labels for fixes
              });
            } else if (title.startsWith('chore')) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['chore'], // Label for chores
              });
            }
